name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: hexpm/elixir:1.10.2-erlang-22.3-alpine-3.11.3

    steps:
    - uses: actions/checkout@v1
    - name: Install git
      run: apt-get install -y git man
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: |
        mix all_tests
